      save_best: True
      plot_agents: True
      verbose: True
      CEMi: True
      

      logger:
            classname: bbrl.utils.logger.TFLogger
            log_dir: ./cem_logs/
            verbose: False
            every_n_seconds: 10

      algorithm:
            policy_dim : 2
            seed: 1
            nb_seeds: 1
            sigma: 0.2
            noise_multiplier: 0.999
            pop_size: 30
            elites_nb: 10
            n_processes: 1
            n_envs: 8
            eval_interval: 2000
            nb_evals: 10
            max_epochs: 40
            nb_runs : 1
            make_plot : True
            diag_covMatrix  : False
            architecture:
                  actor_hidden_size: [4, 4]

      gym_env:
            classname: __main__.make_gym_env
            env_name: CartPole-v1

      optimizer:
            classname: torch.optim.Adam
            lr: 0.001