      save_best: True
      plot_agents: True
      verbose: True
      CEMi: False
      merge : False
      EXPERIMENT : True
      make_plot : True

      logger:
            classname: bbrl.utils.logger.TFLogger
            log_dir: ./cem_logs/
            verbose: False
            every_n_seconds: 10

      algorithm:
            seed: 4
            nb_seeds: 1
            sigma: 0.2
            noise_multiplier: 0.999
            pop_size: 30
            elites_nb: 10
            n_processes: 1
            n_envs: 8
            eval_interval: 2000
            nb_evals: 10
            max_epochs: 30
            nb_runs : 1
            diag_covMatrix  : False
            architecture:
                  actor_hidden_size: [3, 3]

      gym_env:
            classname: __main__.make_gym_env
            env_name: Acrobot-v1

      optimizer:
            classname: torch.optim.Adam
            lr: 0.001
